// CSV fixtures are easier to read as adjacent string literals.
// ignore_for_file: missing_whitespace_between_adjacent_strings

import 'package:flutter_test/flutter_test.dart';
import 'package:tindatrack/features/products/domain/entities/product.dart';
import 'package:tindatrack/features/settings/domain/services/csv_export_builder.dart';
import 'package:tindatrack/features/settings/domain/services/full_restore_parser.dart';
import 'package:tindatrack/features/stock/domain/entities/stock_movement.dart';

void main() {
  const parser = FullRestoreParser();

  test('previews restorable products and stock history files', () {
    final preview = parser.parse(
      productsCsv: _productsCsv,
      stockHistoryCsv: _stockHistoryCsv,
    );

    expect(preview.errors, isEmpty);
    expect(preview.canRestore, isTrue);
    expect(preview.productCount, 2);
    expect(preview.activeProductCount, 1);
    expect(preview.archivedProductCount, 1);
    expect(preview.movementCount, 2);
    expect(preview.products.first.id, 'p1');
    expect(preview.products.first.name, 'Rice');
    expect(preview.products.last.isArchived, isTrue);
    expect(preview.movements.last.type, StockMovementType.stockOut);
    expect(preview.movements.last.reason, StockOutReason.sold);
    expect(preview.movements.last.note, 'Sold, morning rush');
  });

  test('previews csv files generated by CsvExportBuilder', () {
    final bundle = const CsvExportBuilder().build(
      products: [
        Product(
          id: 'p-exported',
          name: 'Coffee',
          category: 'Drinks',
          unit: 'sachet',
          sellingPrice: 12,
          quantity: 8,
          lowStockThreshold: 3,
          barcode: '480',
          isArchived: false,
          createdAt: DateTime.utc(2026, 8, 9, 1),
          updatedAt: DateTime.utc(2026, 8, 9, 2),
        ),
      ],
      movements: [
        StockMovement(
          id: 'm-exported',
          productId: 'p-exported',
          type: StockMovementType.stockOut,
          quantity: 2,
          previousQuantity: 10,
          newQuantity: 8,
          reason: StockOutReason.sold,
          note: 'morning',
          productNameSnapshot: 'Coffee',
          unitSnapshot: 'sachet',
          createdAt: DateTime.utc(2026, 8, 9, 3),
        ),
      ],
      exportedAt: DateTime.utc(2026, 8, 9, 4),
    );

    final preview = parser.parse(
      productsCsv: bundle.productsCsv,
      stockHistoryCsv: bundle.stockHistoryCsv,
    );

    expect(preview.errors, isEmpty);
    expect(preview.canRestore, isTrue);
    expect(preview.products.single.id, 'p-exported');
    expect(preview.movements.single.id, 'm-exported');
  });

  test('reports stock history rows that reference missing products', () {
    final preview = parser.parse(
      productsCsv: _productsCsv,
      stockHistoryCsv: _stockHistoryCsv.replaceAll(',p1,', ',missing-p1,'),
    );

    expect(preview.canRestore, isFalse);
    expect(
      preview.errors.map((error) => error.message).join(' '),
      contains('Product ID missing-p1 was not found'),
    );
  });

  test('requires restorable products export with product id column', () {
    final preview = parser.parse(
      productsCsv:
          'Product Name,Category,Unit,Selling Price,Current Quantity,'
          'Low Stock Threshold,Barcode,Status,Created At,Updated At\n'
          'Rice,Staples,kg,55.50,12,3,123,Active,'
          '2026-08-09 01:00:00 UTC,2026-08-09 01:00:00 UTC\n',
      stockHistoryCsv: _stockHistoryCsv,
    );

    expect(preview.canRestore, isFalse);
    expect(
      preview.errors.any(
        (error) =>
            error.fileName == 'Products CSV' &&
            error.rowNumber == 1 &&
            error.message.contains('restorable'),
      ),
      isTrue,
    );
  });

  test('reports empty stock history file but accepts header-only export', () {
    final emptyPreview = parser.parse(
      productsCsv: _productsCsv,
      stockHistoryCsv: '',
    );

    expect(emptyPreview.canRestore, isFalse);
    expect(
      emptyPreview.errors.map((error) => error.message),
      contains('Stock History CSV file is empty.'),
    );

    final headerOnlyPreview = parser.parse(
      productsCsv: _productsCsv,
      stockHistoryCsv: _stockHistoryHeader,
    );

    expect(headerOnlyPreview.errors, isEmpty);
    expect(headerOnlyPreview.canRestore, isTrue);
    expect(headerOnlyPreview.movementCount, 0);
  });

  test('reports invalid timestamps and movement semantics', () {
    final preview = parser.parse(
      productsCsv: _productsCsv.replaceFirst(
        '2026-08-09 01:00:00 UTC',
        '2026-99-99 99:99:99 UTC',
      ),
      stockHistoryCsv: _stockHistoryCsv
          .replaceFirst('Stock In,,Rice,5,7,12', 'Stock In,Sold,Rice,5,7,12')
          .replaceFirst(
            'Stock Out,Sold,Rice,2,12,10',
            'Stock Out,,Rice,2,12,11',
          ),
    );

    expect(preview.canRestore, isFalse);
    final messages = preview.errors.map((error) => error.message).join(' ');
    expect(
      messages,
      contains('Created At must be a TindaTrack UTC timestamp'),
    );
    expect(messages, contains('Reason must be blank for Stock In'));
    expect(messages, contains('Reason is required for Stock Out'));
    expect(messages, contains('Quantity trail does not match'));
  });

  test('reports duplicate product ids and movement ids', () {
    final preview = parser.parse(
      productsCsv: _productsCsv.replaceFirst('p2,Old Soap', 'p1,Old Soap'),
      stockHistoryCsv: _stockHistoryCsv.replaceFirst('m2,p1', 'm1,p1'),
    );

    expect(preview.canRestore, isFalse);
    final messages = preview.errors.map((error) => error.message).join(' ');
    expect(messages, contains('Product ID p1 appears more than once'));
    expect(messages, contains('Movement ID m1 appears more than once'));
  });
}

const _productsCsv =
    'Product ID,Product Name,Category,Unit,Selling Price,'
    'Current Quantity,Low Stock Threshold,Barcode,Status,'
    'Created At,Updated At\n'
    'p1,Rice,Staples,kg,55.50,12,3,123,Active,'
    '2026-08-09 01:00:00 UTC,2026-08-09 01:00:00 UTC\n'
    'p2,Old Soap,,pcs,18.00,0,2,,Archived,'
    '2026-08-08 01:00:00 UTC,2026-08-08 01:00:00 UTC\n';

const _stockHistoryHeader =
    'Movement ID,Product ID,Date,Type,Reason,'
    'Product Name Snapshot,Quantity,Previous Quantity,New Quantity,'
    'Unit Snapshot,Note\n';

const String _stockHistoryCsv =
    '$_stockHistoryHeader'
    'm1,p1,2026-08-09 02:00:00 UTC,Stock In,,Rice,5,7,12,kg,Restock\n'
    'm2,p1,2026-08-09 03:00:00 UTC,Stock Out,Sold,Rice,2,12,10,kg,'
    '"Sold, morning rush"\n';
